### ISSUE TITLE
Multiple Errors in console

### ISSUE THREAD

**Issue by ALoadOfBS** [sinnwrig/URP-Volumetric-Lighting#4]
First of all, I wanted to say THANK YOU! This is a beautiful asset and adds a ton to my project. Secondly, there are a 85 errors being populated in the console when I run the game. I'm not sure if this is a me issue or this is a bug within the code. I am using Unity Version 2022.3.28f1:

SerializedObjectNotCreatableException: Object at index 0 is null
UnityEditor.Editor.CreateSerializedObject () (at <a675c3b64da6474b9fa5007cb5424433>:0)
UnityEditor.Editor.GetSerializedObjectInternal () (at <a675c3b64da6474b9fa5007cb5424433>:0)
UnityEditor.Editor.get_serializedObject () (at <a675c3b64da6474b9fa5007cb5424433>:0)
Sinnwrig.FogVolumes.Editor.FogVolumeProfileEditor.OnEnable () (at ./Library/PackageCache/com.sinnwrig.fogvolumes@94cacfe659/Editor/FogVolumeProfileEditor.cs:74)

**Comment by ALoadOfBS** [comment]
Errors no longer populating after a restart of unity. Again, Thank you for sharing your work <3

**Comment by sinnwrig** [comment]
Happens to me too. Unfortunately, I think that's a stinky Unity editor bug that I don't think I can do much about. If it keeps occurring, tell me, and I'll try and find a solution. Glad to hear restarting the editor worked for you though!
